config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    collection do
      get :search
    end
    resources :comments, only: [:create, :destroy]
  end
  
  resources :users do
    resources :profiles, only: [:new, :create, :show] do
      member do
        get :following, :followers
      end
    end
  end

  devise_for :users, path: "accounts", controllers: {
    registrations: 'users/registrations'
  }
  
  resources :relationships, only: [:create, :destroy]

  get '/feed', to: 'profiles#feed', as: :feed, defaults: { format: 'atom' }
  get 'tags/:tag', to: 'posts#index', as: :tag
  #get 'search', to: 'posts#search', as: :search

  root to: 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  delegate :email, to: :user, prefix: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  validates :user, :presence => true
  default_scope { order("created_at DESC") }

  delegate :email, to: :user, prefix: true

  acts_as_taggable

  searchable do
    text :title
  end

  def owned_by?(owner)
    user.id == owner.id
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates :user, presence: true
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :followed_id, presence: true
  validates :follower_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  

  has_many :posts
  has_many :comments
  has_many :active_relationships, class_name: "Relationship", 
            foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
            foreign_key: "followed_id", dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_one :profile 

  delegate :name, to: :profile, prefix: true


  def following?(other)
    following.include?(other)
  end

  def follow(other)
    active_relationships.create(followed_id: other.id)
  end

  def unfollow(other)
    active_relationships.find_by(followed_id: other.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post


  def create
    @comment = @post.comments.build(comments_params)
    @comment.user = current_user
    if @comment.save
      respond_to do |wants|
        wants.html do
          flash[:notice] = "Commented created."
          redirect_to @post
        end
        wants.js
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html do
        flash[:success] = 'Comment deleted.'
        redirect_to @post
      end
      format.js
    end
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def comments_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :search]

  respond_to :html

  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.all
    end
    respond_with(@posts)
  end

  def search
    @search = Post.search do
      fulltext params[:search]
    end
    @posts = @search.results
    render 'index'
  end

  def show
    @comment = @post.comments.build
    respond_with(@post)
  end

  def new
    @post = Post.new
    respond_with(@post)
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    flash[:notice] = "Post has been created." if @post.save
    respond_with(@post)
  end

  def update
    @post.update(post_params) if @post.owned_by?(current_user)
    respond_with(@post)
  end

  def destroy
    @post.destroy if @post.owned_by?(current_user)
    respond_with(@post)
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body, :tag_list)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: [:following, :followers, :show, :feed]
  before_action :authenticate_user!

  def following
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @users = @user.followers
    render 'show_follow'
  end

  def feed
    @title = "Feed of #{@user.profile_name}"
    @posts = @user.posts
    @updated = @posts.first.updated_at unless @posts.empty?
    
    respond_to do |format|
      format.atom { render layout: false }
      format.rss { redirect_to feed_path(format: :atom), status: :moved_permanently }
    end
  end
  
  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      respond_to do |wants|
        wants.html do
          flash[:notice] = "Profile created."
          redirect_to posts_path
        end
      end
    end
  end

  def new
    @profile = current_user.build_profile
  end

  def show
    @profile = @user.profile
  end

  private

  def profile_params
    params.require(:profile).permit(:name, :address, :bio)
  end

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    FollowMailer.send_message(current_user, @user).deliver_now
    respond_to do |f|
      f.html { redirect_to root_path }
      f.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    respond_to do |f|
      f.html { redirect_to root_path }
      f.js
    end
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    new_user_profile_path(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png"
  end

  def show_profile
    yield if current_user.profile.try(:name)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def show_tags(post)
    raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')
  end

  def owner?(post)
    post.user == current_user
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
  <h6>Author:<%= comment.user_email %></h6>
  <%= image_tag avatar_url(comment.user) %>
  <%= simple_format(comment.body) %>
  <%= link_to "Delete comment", post_comment_path(comment.post, comment), method: :delete, remote: true %>
<% end %>

app/views/comments/_form.html.erb
<strong>New Comment</strong>
  <%= form_for [@post, @comment], remote: true do |f| %>
  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>
  
  <%= f.submit "Create comment" %>
<% end %>

app/views/comments/create.js.erb
var comments_list = $('#comments-list');
comments_list.append('<%= escape_javascript(render partial: @comment) %>');
comments_list.find('div:last-child').addClass('last-comment');
$('#comments-count').html('This article has <%= escape_javascript(pluralize(@post.comments.count, 'comment')) %>');
$('#comment-form').html('<%= escape_javascript(render('comments/form')) %>');

app/views/comments/destroy.js.erb
$('#comments-list').html('<%= escape_javascript(render partial: @post.comments) %>');
$('#comments-count').html('This article has <%= escape_javascript(pluralize(@post.comments.count, 'comment')) %>');

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<div class="container">
  <nav class="blog-nav">
    <%= render 'layouts/navigation_links' %>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<%= link_to 'About', page_path('about') %>
<%= link_to 'Home Page', root_path %>

<% if user_signed_in? %>
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
  
  <% show_profile do %>
    <%= link_to "MyProfile", user_profile_path(current_user, current_user.profile) %>
  <% end %>

<% else %>
  <%= link_to "Sign in", new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blog" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Blog" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="blog-masthead">
      <%= render 'layouts/navigation' %>
    </div>
    <div class="container">
      <div class="blog-header">
        <h1 class="blog-title">My First Blog</h1>
        <p class="lead blog-description">I'm back bitches, and this time I'm gonna rock</p>
      </div>
      

      <%= render 'layouts/messages' %>
      

      <div class="row">
        <div class="col-sm-8 blog-main">
          <%= yield %>
        </div>
        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
            <%= render 'posts/search' %>
        </div>
      </div>
    


    </div>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
  </div>

  <div>
    <%= f.input :tag_list %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Post it!" %>
  </div>
<% end %>

app/views/posts/_posts.html.erb
<% posts.each do |post| %>
  <h3 class="blog-post-title"><%= post.title %></h3>
  <p class="blog-post-meta">By: <%= link_to post.user_email, user_profile_path(post.user.profile, post.user) %></p>
  <p><%= simple_format(post.body) %></p>
  <%= link_to "Read more", post_path(post) %>
  <hr> 
<% end %>

app/views/posts/_search.html.erb
<%= form_tag(search_posts_path, method: :get) do %>
  <%= text_field_tag :search %>
  <%= submit_tag "Search", name: nil %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render partial: 'posts', locals: {posts: @posts } %>

<% if user_signed_in? %>
  <%= link_to 'New Post', new_post_path %>  
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="col-sm-8 blog-main">
  <div class="blog-post">
    <h3 class="blog-post-title"><%= @post.title %></h3>
    <p class="blog-post-meta">By: <%= @post.user_email %></p>
  
    <p><%= simple_format(@post.body) %></p>

    <div>
      <%= show_tags(@post) %>
    </div>
    <div> 
    </div>
      
    <nav>
      <ul class="pager">
      <% if owner?(@post) %>
        <li><%= link_to 'Edit', edit_post_path(@post) %></li>
      <% end %>
        <li><%= link_to 'Back', posts_path %></li>
      </ul>
    </nav>

    <h3 align="center">Comments:</h3>
    <br />
    <div id="comments-list">
      <%= render partial: @post.reload.comments %>
    </div>

    <div id="comment-form">
      <%= render 'comments/form' %>
    </div>
  </div>

app/views/profiles/_follow_form.html.erb
<div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= form_for(current_user.active_relationships.find_by(followed_id: @user.id), method: :delete, remote: true) do |f| %>
      <%= f.submit "Unfollow", class: "btn" %>
    <% end %>
  <% else %>
    <%= form_for(current_user.active_relationships.build(followed_id: @user.id), remote: true) do |f| %>
      <%= hidden_field_tag :followed_id, @user.id %>
      <%= f.submit "Follow", class: "btn bnt-primary" %>
    <% end %>
  <% end %>
</div>

app/views/profiles/new.html.erb
<strong>New Profile for: <%= current_user.email %></strong>
  <%= form_for [current_user, @profile] do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

    <p>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </p>

    <p>
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </p>
  <%= f.submit "Create profile" %>
<% end %>

app/views/profiles/show.html.erb
<h1>User: <%= @profile.name %></h1>
<%= image_tag avatar_url(@user) %>
<%= render 'follow_form' %>

<% @user.posts.each do |post| %>
  <%= link_to post.title, post_path(post) %>
<% end %>

<div class="stats">
  <a href="<%= following_user_profile_path(@user, @profile) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_profile_path(@user, @profile) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

<div>
  <% if @user.posts.any? %>
    <%= render partial: 'posts/posts', locals: { posts: @user.posts} %>
  <% else %>
    <strong>There is no posts by: <%= @profile.name %></strong>
  <% end %>
</div>

app/views/profiles/show_follow.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="profile_info">
      <%= image_tag (avatar_url(@user)) %>
      <h1><%= @user.profile_name %></h1>
      <span><%= link_to "view my profile", [@user, @user.profile] %></span>
      <span><b>Posts:</b> <%= link_to @user.posts.count %></span>
      <strong>users:</strong>
    </section>
    <section class="stats">
      <% if @users.any? %>
        <div class="profile_avatars">
          <% @users.each do |user| %>
            <%= link_to image_tag(avatar_url(user)), [user, user.profile]  %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
  </div>
</div>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('profiles/follow_form')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('profiles/follow_form')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<%= link_to "New Post", new_post_path %>
<%= link_to "New User", new_user_registration_path %>